package erpsolscm.erpsolscmmodel.erpsolscmvo;

import erpsolscm.erpsolscmmodel.erpsolscmeo.PuPoLinesImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 17 18:04:02 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PuPoLinesVORowImpl extends ViewRowImpl {

    public static final int ENTITY_PUPOLINES = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Poitemid,
        Poid,
        Dmditemid,
        Itemid,
        ItemType,
        DemandQty,
        OrderQty,
        ConfirmedQty,
        CancelQty,
        DeliveryDate,
        UnitPriceInFcurr,
        UnitPriceInBcurr,
        Hscode,
        HsRate,
        Remarks,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Polineno,
        Partid,
        GrnQty,
        LcNo,
        GdNo,
        AirwaysBillno,
        GrnNo,
        FocQty,
        ExtraQty,
        RefLcNo,
        ActPriceInFcurr,
        ActPriceInBcurr,
        MemoBillid,
        SaleTax,
        Discount,
        NetAmount,
        BarCode,
        GrossAmount,
        ExtraTax,
        Poseq,
        Polinesseq,
        txtModelNo,
        txtNetAmount,
        txtGrossAmount,
        txtProductId,
        txtPosted,
        InItemsView,
        PuPurchaseOrderImeiVO,
        PuPurchaseOrdersVO,
        AccInItemsView;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int POITEMID = AttributesEnum.Poitemid.index();
    public static final int POID = AttributesEnum.Poid.index();
    public static final int DMDITEMID = AttributesEnum.Dmditemid.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int ITEMTYPE = AttributesEnum.ItemType.index();
    public static final int DEMANDQTY = AttributesEnum.DemandQty.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int CONFIRMEDQTY = AttributesEnum.ConfirmedQty.index();
    public static final int CANCELQTY = AttributesEnum.CancelQty.index();
    public static final int DELIVERYDATE = AttributesEnum.DeliveryDate.index();
    public static final int UNITPRICEINFCURR = AttributesEnum.UnitPriceInFcurr.index();
    public static final int UNITPRICEINBCURR = AttributesEnum.UnitPriceInBcurr.index();
    public static final int HSCODE = AttributesEnum.Hscode.index();
    public static final int HSRATE = AttributesEnum.HsRate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int POLINENO = AttributesEnum.Polineno.index();
    public static final int PARTID = AttributesEnum.Partid.index();
    public static final int GRNQTY = AttributesEnum.GrnQty.index();
    public static final int LCNO = AttributesEnum.LcNo.index();
    public static final int GDNO = AttributesEnum.GdNo.index();
    public static final int AIRWAYSBILLNO = AttributesEnum.AirwaysBillno.index();
    public static final int GRNNO = AttributesEnum.GrnNo.index();
    public static final int FOCQTY = AttributesEnum.FocQty.index();
    public static final int EXTRAQTY = AttributesEnum.ExtraQty.index();
    public static final int REFLCNO = AttributesEnum.RefLcNo.index();
    public static final int ACTPRICEINFCURR = AttributesEnum.ActPriceInFcurr.index();
    public static final int ACTPRICEINBCURR = AttributesEnum.ActPriceInBcurr.index();
    public static final int MEMOBILLID = AttributesEnum.MemoBillid.index();
    public static final int SALETAX = AttributesEnum.SaleTax.index();
    public static final int DISCOUNT = AttributesEnum.Discount.index();
    public static final int NETAMOUNT = AttributesEnum.NetAmount.index();
    public static final int BARCODE = AttributesEnum.BarCode.index();
    public static final int GROSSAMOUNT = AttributesEnum.GrossAmount.index();
    public static final int EXTRATAX = AttributesEnum.ExtraTax.index();
    public static final int POSEQ = AttributesEnum.Poseq.index();
    public static final int POLINESSEQ = AttributesEnum.Polinesseq.index();
    public static final int TXTMODELNO = AttributesEnum.txtModelNo.index();
    public static final int TXTNETAMOUNT = AttributesEnum.txtNetAmount.index();
    public static final int TXTGROSSAMOUNT = AttributesEnum.txtGrossAmount.index();
    public static final int TXTPRODUCTID = AttributesEnum.txtProductId.index();
    public static final int TXTPOSTED = AttributesEnum.txtPosted.index();
    public static final int INITEMSVIEW = AttributesEnum.InItemsView.index();
    public static final int PUPURCHASEORDERIMEIVO = AttributesEnum.PuPurchaseOrderImeiVO.index();
    public static final int PUPURCHASEORDERSVO = AttributesEnum.PuPurchaseOrdersVO.index();
    public static final int ACCINITEMSVIEW = AttributesEnum.AccInItemsView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PuPoLinesVORowImpl() {
    }

    /**
     * Gets PuPoLines entity object.
     * @return the PuPoLines
     */
    public PuPoLinesImpl getPuPoLines() {
        return (PuPoLinesImpl) getEntity(ENTITY_PUPOLINES);
    }

    /**
     * Gets the attribute value for POITEMID using the alias name Poitemid.
     * @return the POITEMID
     */
    public String getPoitemid() {
        return (String) getAttributeInternal(POITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for POITEMID using the alias name Poitemid.
     * @param value value to set the POITEMID
     */
    public void setPoitemid(String value) {
        setAttributeInternal(POITEMID, value);
    }

    /**
     * Gets the attribute value for POID using the alias name Poid.
     * @return the POID
     */
    public String getPoid() {
        return (String) getAttributeInternal(POID);
    }

    /**
     * Sets <code>value</code> as attribute value for POID using the alias name Poid.
     * @param value value to set the POID
     */
    public void setPoid(String value) {
        setAttributeInternal(POID, value);
    }

    /**
     * Gets the attribute value for DMDITEMID using the alias name Dmditemid.
     * @return the DMDITEMID
     */
    public String getDmditemid() {
        return (String) getAttributeInternal(DMDITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for DMDITEMID using the alias name Dmditemid.
     * @param value value to set the DMDITEMID
     */
    public void setDmditemid(String value) {
        setAttributeInternal(DMDITEMID, value);
    }

    /**
     * Gets the attribute value for ITEMID using the alias name Itemid.
     * @return the ITEMID
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEMID using the alias name Itemid.
     * @param value value to set the ITEMID
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for ITEM_TYPE using the alias name ItemType.
     * @return the ITEM_TYPE
     */
    public String getItemType() {
        return (String) getAttributeInternal(ITEMTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_TYPE using the alias name ItemType.
     * @param value value to set the ITEM_TYPE
     */
    public void setItemType(String value) {
        setAttributeInternal(ITEMTYPE, value);
    }

    /**
     * Gets the attribute value for DEMAND_QTY using the alias name DemandQty.
     * @return the DEMAND_QTY
     */
    public Integer getDemandQty() {
        return (Integer) getAttributeInternal(DEMANDQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for DEMAND_QTY using the alias name DemandQty.
     * @param value value to set the DEMAND_QTY
     */
    public void setDemandQty(Integer value) {
        setAttributeInternal(DEMANDQTY, value);
    }

    /**
     * Gets the attribute value for ORDER_QTY using the alias name OrderQty.
     * @return the ORDER_QTY
     */
    public Integer getOrderQty() {
        return (Integer) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_QTY using the alias name OrderQty.
     * @param value value to set the ORDER_QTY
     */
    public void setOrderQty(Integer value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for CONFIRMED_QTY using the alias name ConfirmedQty.
     * @return the CONFIRMED_QTY
     */
    public Integer getConfirmedQty() {
        return (Integer) getAttributeInternal(CONFIRMEDQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for CONFIRMED_QTY using the alias name ConfirmedQty.
     * @param value value to set the CONFIRMED_QTY
     */
    public void setConfirmedQty(Integer value) {
        setAttributeInternal(CONFIRMEDQTY, value);
    }

    /**
     * Gets the attribute value for CANCEL_QTY using the alias name CancelQty.
     * @return the CANCEL_QTY
     */
    public Integer getCancelQty() {
        return (Integer) getAttributeInternal(CANCELQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for CANCEL_QTY using the alias name CancelQty.
     * @param value value to set the CANCEL_QTY
     */
    public void setCancelQty(Integer value) {
        setAttributeInternal(CANCELQTY, value);
    }

    /**
     * Gets the attribute value for DELIVERY_DATE using the alias name DeliveryDate.
     * @return the DELIVERY_DATE
     */
    public Date getDeliveryDate() {
        return (Date) getAttributeInternal(DELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_DATE using the alias name DeliveryDate.
     * @param value value to set the DELIVERY_DATE
     */
    public void setDeliveryDate(Date value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for UNIT_PRICE_IN_FCURR using the alias name UnitPriceInFcurr.
     * @return the UNIT_PRICE_IN_FCURR
     */
    public BigDecimal getUnitPriceInFcurr() {
        return (BigDecimal) getAttributeInternal(UNITPRICEINFCURR);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_PRICE_IN_FCURR using the alias name UnitPriceInFcurr.
     * @param value value to set the UNIT_PRICE_IN_FCURR
     */
    public void setUnitPriceInFcurr(BigDecimal value) {
        setAttributeInternal(UNITPRICEINFCURR, value);
    }

    /**
     * Gets the attribute value for UNIT_PRICE_IN_BCURR using the alias name UnitPriceInBcurr.
     * @return the UNIT_PRICE_IN_BCURR
     */
    public BigDecimal getUnitPriceInBcurr() {
        return (BigDecimal) getAttributeInternal(UNITPRICEINBCURR);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_PRICE_IN_BCURR using the alias name UnitPriceInBcurr.
     * @param value value to set the UNIT_PRICE_IN_BCURR
     */
    public void setUnitPriceInBcurr(BigDecimal value) {
        setAttributeInternal(UNITPRICEINBCURR, value);
    }

    /**
     * Gets the attribute value for HSCODE using the alias name Hscode.
     * @return the HSCODE
     */
    public String getHscode() {
        return (String) getAttributeInternal(HSCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for HSCODE using the alias name Hscode.
     * @param value value to set the HSCODE
     */
    public void setHscode(String value) {
        setAttributeInternal(HSCODE, value);
    }

    /**
     * Gets the attribute value for HS_RATE using the alias name HsRate.
     * @return the HS_RATE
     */
    public BigDecimal getHsRate() {
        return (BigDecimal) getAttributeInternal(HSRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for HS_RATE using the alias name HsRate.
     * @param value value to set the HS_RATE
     */
    public void setHsRate(BigDecimal value) {
        setAttributeInternal(HSRATE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for POLINENO using the alias name Polineno.
     * @return the POLINENO
     */
    public Integer getPolineno() {
        return (Integer) getAttributeInternal(POLINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for POLINENO using the alias name Polineno.
     * @param value value to set the POLINENO
     */
    public void setPolineno(Integer value) {
        setAttributeInternal(POLINENO, value);
    }

    /**
     * Gets the attribute value for PARTID using the alias name Partid.
     * @return the PARTID
     */
    public String getPartid() {
        return (String) getAttributeInternal(PARTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTID using the alias name Partid.
     * @param value value to set the PARTID
     */
    public void setPartid(String value) {
        setAttributeInternal(PARTID, value);
    }

    /**
     * Gets the attribute value for GRN_QTY using the alias name GrnQty.
     * @return the GRN_QTY
     */
    public Integer getGrnQty() {
        return (Integer) getAttributeInternal(GRNQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for GRN_QTY using the alias name GrnQty.
     * @param value value to set the GRN_QTY
     */
    public void setGrnQty(Integer value) {
        setAttributeInternal(GRNQTY, value);
    }

    /**
     * Gets the attribute value for LC_NO using the alias name LcNo.
     * @return the LC_NO
     */
    public String getLcNo() {
        return (String) getAttributeInternal(LCNO);
    }

    /**
     * Sets <code>value</code> as attribute value for LC_NO using the alias name LcNo.
     * @param value value to set the LC_NO
     */
    public void setLcNo(String value) {
        setAttributeInternal(LCNO, value);
    }

    /**
     * Gets the attribute value for GD_NO using the alias name GdNo.
     * @return the GD_NO
     */
    public String getGdNo() {
        return (String) getAttributeInternal(GDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GD_NO using the alias name GdNo.
     * @param value value to set the GD_NO
     */
    public void setGdNo(String value) {
        setAttributeInternal(GDNO, value);
    }

    /**
     * Gets the attribute value for AIRWAYS_BILLNO using the alias name AirwaysBillno.
     * @return the AIRWAYS_BILLNO
     */
    public String getAirwaysBillno() {
        return (String) getAttributeInternal(AIRWAYSBILLNO);
    }

    /**
     * Sets <code>value</code> as attribute value for AIRWAYS_BILLNO using the alias name AirwaysBillno.
     * @param value value to set the AIRWAYS_BILLNO
     */
    public void setAirwaysBillno(String value) {
        setAttributeInternal(AIRWAYSBILLNO, value);
    }

    /**
     * Gets the attribute value for GRN_NO using the alias name GrnNo.
     * @return the GRN_NO
     */
    public String getGrnNo() {
        return (String) getAttributeInternal(GRNNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GRN_NO using the alias name GrnNo.
     * @param value value to set the GRN_NO
     */
    public void setGrnNo(String value) {
        setAttributeInternal(GRNNO, value);
    }

    /**
     * Gets the attribute value for FOC_QTY using the alias name FocQty.
     * @return the FOC_QTY
     */
    public Integer getFocQty() {
        return (Integer) getAttributeInternal(FOCQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for FOC_QTY using the alias name FocQty.
     * @param value value to set the FOC_QTY
     */
    public void setFocQty(Integer value) {
        setAttributeInternal(FOCQTY, value);
    }

    /**
     * Gets the attribute value for EXTRA_QTY using the alias name ExtraQty.
     * @return the EXTRA_QTY
     */
    public Integer getExtraQty() {
        return (Integer) getAttributeInternal(EXTRAQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for EXTRA_QTY using the alias name ExtraQty.
     * @param value value to set the EXTRA_QTY
     */
    public void setExtraQty(Integer value) {
        setAttributeInternal(EXTRAQTY, value);
    }

    /**
     * Gets the attribute value for REF_LC_NO using the alias name RefLcNo.
     * @return the REF_LC_NO
     */
    public String getRefLcNo() {
        return (String) getAttributeInternal(REFLCNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_LC_NO using the alias name RefLcNo.
     * @param value value to set the REF_LC_NO
     */
    public void setRefLcNo(String value) {
        setAttributeInternal(REFLCNO, value);
    }

    /**
     * Gets the attribute value for ACT_PRICE_IN_FCURR using the alias name ActPriceInFcurr.
     * @return the ACT_PRICE_IN_FCURR
     */
    public BigDecimal getActPriceInFcurr() {
        return (BigDecimal) getAttributeInternal(ACTPRICEINFCURR);
    }

    /**
     * Sets <code>value</code> as attribute value for ACT_PRICE_IN_FCURR using the alias name ActPriceInFcurr.
     * @param value value to set the ACT_PRICE_IN_FCURR
     */
    public void setActPriceInFcurr(BigDecimal value) {
        setAttributeInternal(ACTPRICEINFCURR, value);
    }

    /**
     * Gets the attribute value for ACT_PRICE_IN_BCURR using the alias name ActPriceInBcurr.
     * @return the ACT_PRICE_IN_BCURR
     */
    public BigDecimal getActPriceInBcurr() {
        return (BigDecimal) getAttributeInternal(ACTPRICEINBCURR);
    }

    /**
     * Sets <code>value</code> as attribute value for ACT_PRICE_IN_BCURR using the alias name ActPriceInBcurr.
     * @param value value to set the ACT_PRICE_IN_BCURR
     */
    public void setActPriceInBcurr(BigDecimal value) {
        setAttributeInternal(ACTPRICEINBCURR, value);
    }

    /**
     * Gets the attribute value for MEMO_BILLID using the alias name MemoBillid.
     * @return the MEMO_BILLID
     */
    public String getMemoBillid() {
        return (String) getAttributeInternal(MEMOBILLID);
    }

    /**
     * Sets <code>value</code> as attribute value for MEMO_BILLID using the alias name MemoBillid.
     * @param value value to set the MEMO_BILLID
     */
    public void setMemoBillid(String value) {
        setAttributeInternal(MEMOBILLID, value);
    }

    /**
     * Gets the attribute value for SALE_TAX using the alias name SaleTax.
     * @return the SALE_TAX
     */
    public BigDecimal getSaleTax() {
        return (BigDecimal) getAttributeInternal(SALETAX);
    }

    /**
     * Sets <code>value</code> as attribute value for SALE_TAX using the alias name SaleTax.
     * @param value value to set the SALE_TAX
     */
    public void setSaleTax(BigDecimal value) {
        setAttributeInternal(SALETAX, value);
    }

    /**
     * Gets the attribute value for DISCOUNT using the alias name Discount.
     * @return the DISCOUNT
     */
    public BigDecimal getDiscount() {
        return (BigDecimal) getAttributeInternal(DISCOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for DISCOUNT using the alias name Discount.
     * @param value value to set the DISCOUNT
     */
    public void setDiscount(BigDecimal value) {
        setAttributeInternal(DISCOUNT, value);
    }

    /**
     * Gets the attribute value for NET_AMOUNT using the alias name NetAmount.
     * @return the NET_AMOUNT
     */
    public BigDecimal getNetAmount() {
        return (BigDecimal) getAttributeInternal(NETAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for NET_AMOUNT using the alias name NetAmount.
     * @param value value to set the NET_AMOUNT
     */
    public void setNetAmount(BigDecimal value) {
        setAttributeInternal(NETAMOUNT, value);
    }

    /**
     * Gets the attribute value for BAR_CODE using the alias name BarCode.
     * @return the BAR_CODE
     */
    public String getBarCode() {
        return (String) getAttributeInternal(BARCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for BAR_CODE using the alias name BarCode.
     * @param value value to set the BAR_CODE
     */
    public void setBarCode(String value) {
        setAttributeInternal(BARCODE, value);
    }

    /**
     * Gets the attribute value for GROSS_AMOUNT using the alias name GrossAmount.
     * @return the GROSS_AMOUNT
     */
    public BigDecimal getGrossAmount() {
        return (BigDecimal) getAttributeInternal(GROSSAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for GROSS_AMOUNT using the alias name GrossAmount.
     * @param value value to set the GROSS_AMOUNT
     */
    public void setGrossAmount(BigDecimal value) {
        setAttributeInternal(GROSSAMOUNT, value);
    }

    /**
     * Gets the attribute value for EXTRA_TAX using the alias name ExtraTax.
     * @return the EXTRA_TAX
     */
    public BigDecimal getExtraTax() {
        return (BigDecimal) getAttributeInternal(EXTRATAX);
    }

    /**
     * Sets <code>value</code> as attribute value for EXTRA_TAX using the alias name ExtraTax.
     * @param value value to set the EXTRA_TAX
     */
    public void setExtraTax(BigDecimal value) {
        setAttributeInternal(EXTRATAX, value);
    }

    /**
     * Gets the attribute value for POSEQ using the alias name Poseq.
     * @return the POSEQ
     */
    public Integer getPoseq() {
        return (Integer) getAttributeInternal(POSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for POSEQ using the alias name Poseq.
     * @param value value to set the POSEQ
     */
    public void setPoseq(Integer value) {
        setAttributeInternal(POSEQ, value);
    }

    /**
     * Gets the attribute value for POLINESSEQ using the alias name Polinesseq.
     * @return the POLINESSEQ
     */
    public Integer getPolinesseq() {
        return (Integer) getAttributeInternal(POLINESSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for POLINESSEQ using the alias name Polinesseq.
     * @param value value to set the POLINESSEQ
     */
    public void setPolinesseq(Integer value) {
        setAttributeInternal(POLINESSEQ, value);
    }

    /**
     * Gets the attribute value for TXT_MODEL_NO using the alias name txtModelNo.
     * @return the TXT_MODEL_NO
     */
    public String gettxtModelNo() {
        return (String) getAttributeInternal(TXTMODELNO);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_MODEL_NO using the alias name txtModelNo.
     * @param value value to set the TXT_MODEL_NO
     */
    public void settxtModelNo(String value) {
        setAttributeInternal(TXTMODELNO, value);
    }

    /**
     * Gets the attribute value for TXT_NET_AMOUNT using the alias name txtNetAmount.
     * @return the TXT_NET_AMOUNT
     */
    public BigDecimal gettxtNetAmount() {
        return (BigDecimal) getAttributeInternal(TXTNETAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_NET_AMOUNT using the alias name txtNetAmount.
     * @param value value to set the TXT_NET_AMOUNT
     */
    public void settxtNetAmount(BigDecimal value) {
        setAttributeInternal(TXTNETAMOUNT, value);
    }

    /**
     * Gets the attribute value for TXT_GROSS_AMOUNT using the alias name txtGrossAmount.
     * @return the TXT_GROSS_AMOUNT
     */
    public BigDecimal gettxtGrossAmount() {
        return (BigDecimal) getAttributeInternal(TXTGROSSAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_GROSS_AMOUNT using the alias name txtGrossAmount.
     * @param value value to set the TXT_GROSS_AMOUNT
     */
    public void settxtGrossAmount(BigDecimal value) {
        setAttributeInternal(TXTGROSSAMOUNT, value);
    }

    /**
     * Gets the attribute value for TXT_PRODUCT_ID using the alias name txtProductId.
     * @return the TXT_PRODUCT_ID
     */
    public String gettxtProductId() {
        return (String) getAttributeInternal(TXTPRODUCTID);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PRODUCT_ID using the alias name txtProductId.
     * @param value value to set the TXT_PRODUCT_ID
     */
    public void settxtProductId(String value) {
        setAttributeInternal(TXTPRODUCTID, value);
    }

    /**
     * Gets the attribute value for TXT_POSTED using the alias name txtPosted.
     * @return the TXT_POSTED
     */
    public String gettxtPosted() {
        return (String) getAttributeInternal(TXTPOSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_POSTED using the alias name txtPosted.
     * @param value value to set the TXT_POSTED
     */
    public void settxtPosted(String value) {
        setAttributeInternal(TXTPOSTED, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InItemsView.
     */
    public Row getInItemsView() {
        return (Row) getAttributeInternal(INITEMSVIEW);
    }

    /**
     * Sets the master-detail link InItemsView between this object and <code>value</code>.
     */
    public void setInItemsView(Row value) {
        setAttributeInternal(INITEMSVIEW, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PuPurchaseOrderImeiVO.
     */
    public RowIterator getPuPurchaseOrderImeiVO() {
        return (RowIterator) getAttributeInternal(PUPURCHASEORDERIMEIVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link PuPurchaseOrdersVO.
     */
    public Row getPuPurchaseOrdersVO() {
        return (Row) getAttributeInternal(PUPURCHASEORDERSVO);
    }

    /**
     * Sets the master-detail link PuPurchaseOrdersVO between this object and <code>value</code>.
     */
    public void setPuPurchaseOrdersVO(Row value) {
        setAttributeInternal(PUPURCHASEORDERSVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccInItemsView.
     */
    public RowSet getAccInItemsView() {
        return (RowSet) getAttributeInternal(ACCINITEMSVIEW);
    }
    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getPuPurchaseOrdersVO().getAttribute("Posted").equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

