package erpsolscm.erpsolscmmodel.erpsolscmvo;

import erpsolscm.erpsolscmmodel.erpsolscmeo.PuPurchaseOrdersImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 17 18:02:54 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PuPurchaseOrdersVORowImpl extends ViewRowImpl {

    public static final int ENTITY_PUPURCHASEORDERS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Poid,
        Locationid,
        Supplierid,
        Currcode,
        Deliverytermid,
        Paymenttermid,
        ReceStoreid,
        PoDate,
        Potype,
        Postatus,
        SuppRefno,
        SuppRefDate,
        ExchangeRate,
        Remarks,
        Posted,
        Postedby,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        PoFor,
        ProdId,
        LcBankid,
        LcBranchid,
        LcRef,
        LcForId,
        IsMigrated,
        MigratedDate,
        RefOrderHeaderId,
        CycleFor,
        ApprovedMemoWolcId,
        Poseq,
        txtLocationName,
        txtStoreName,
        txtSupplierName,
        txtSumQuantity,
        txtSumNetmount,
        txtSumGrossAmount,
        PuPoLinesVO,
        AllLocationsView,
        AllStoresView,
        PuSuppliersView,
        AccAllPaymentTermsVO,
        AccAllDeliveryTermsVO,
        AccAllLocationsView,
        AccAllStoresVO,
        AccPuSuppliersView;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int POID = AttributesEnum.Poid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int SUPPLIERID = AttributesEnum.Supplierid.index();
    public static final int CURRCODE = AttributesEnum.Currcode.index();
    public static final int DELIVERYTERMID = AttributesEnum.Deliverytermid.index();
    public static final int PAYMENTTERMID = AttributesEnum.Paymenttermid.index();
    public static final int RECESTOREID = AttributesEnum.ReceStoreid.index();
    public static final int PODATE = AttributesEnum.PoDate.index();
    public static final int POTYPE = AttributesEnum.Potype.index();
    public static final int POSTATUS = AttributesEnum.Postatus.index();
    public static final int SUPPREFNO = AttributesEnum.SuppRefno.index();
    public static final int SUPPREFDATE = AttributesEnum.SuppRefDate.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDBY = AttributesEnum.Postedby.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int POFOR = AttributesEnum.PoFor.index();
    public static final int PRODID = AttributesEnum.ProdId.index();
    public static final int LCBANKID = AttributesEnum.LcBankid.index();
    public static final int LCBRANCHID = AttributesEnum.LcBranchid.index();
    public static final int LCREF = AttributesEnum.LcRef.index();
    public static final int LCFORID = AttributesEnum.LcForId.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int REFORDERHEADERID = AttributesEnum.RefOrderHeaderId.index();
    public static final int CYCLEFOR = AttributesEnum.CycleFor.index();
    public static final int APPROVEDMEMOWOLCID = AttributesEnum.ApprovedMemoWolcId.index();
    public static final int POSEQ = AttributesEnum.Poseq.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTSTORENAME = AttributesEnum.txtStoreName.index();
    public static final int TXTSUPPLIERNAME = AttributesEnum.txtSupplierName.index();
    public static final int TXTSUMQUANTITY = AttributesEnum.txtSumQuantity.index();
    public static final int TXTSUMNETMOUNT = AttributesEnum.txtSumNetmount.index();
    public static final int TXTSUMGROSSAMOUNT = AttributesEnum.txtSumGrossAmount.index();
    public static final int PUPOLINESVO = AttributesEnum.PuPoLinesVO.index();
    public static final int ALLLOCATIONSVIEW = AttributesEnum.AllLocationsView.index();
    public static final int ALLSTORESVIEW = AttributesEnum.AllStoresView.index();
    public static final int PUSUPPLIERSVIEW = AttributesEnum.PuSuppliersView.index();
    public static final int ACCALLPAYMENTTERMSVO = AttributesEnum.AccAllPaymentTermsVO.index();
    public static final int ACCALLDELIVERYTERMSVO = AttributesEnum.AccAllDeliveryTermsVO.index();
    public static final int ACCALLLOCATIONSVIEW = AttributesEnum.AccAllLocationsView.index();
    public static final int ACCALLSTORESVO = AttributesEnum.AccAllStoresVO.index();
    public static final int ACCPUSUPPLIERSVIEW = AttributesEnum.AccPuSuppliersView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PuPurchaseOrdersVORowImpl() {
    }

    /**
     * Gets PuPurchaseOrders entity object.
     * @return the PuPurchaseOrders
     */
    public PuPurchaseOrdersImpl getPuPurchaseOrders() {
        return (PuPurchaseOrdersImpl) getEntity(ENTITY_PUPURCHASEORDERS);
    }

    /**
     * Gets the attribute value for POID using the alias name Poid.
     * @return the POID
     */
    public String getPoid() {
        return (String) getAttributeInternal(POID);
    }

    /**
     * Sets <code>value</code> as attribute value for POID using the alias name Poid.
     * @param value value to set the POID
     */
    public void setPoid(String value) {
        setAttributeInternal(POID, value);
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for SUPPLIERID using the alias name Supplierid.
     * @return the SUPPLIERID
     */
    public String getSupplierid() {
        return (String) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIERID using the alias name Supplierid.
     * @param value value to set the SUPPLIERID
     */
    public void setSupplierid(String value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for CURRCODE using the alias name Currcode.
     * @return the CURRCODE
     */
    public String getCurrcode() {
        return (String) getAttributeInternal(CURRCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRCODE using the alias name Currcode.
     * @param value value to set the CURRCODE
     */
    public void setCurrcode(String value) {
        setAttributeInternal(CURRCODE, value);
    }

    /**
     * Gets the attribute value for DELIVERYTERMID using the alias name Deliverytermid.
     * @return the DELIVERYTERMID
     */
    public String getDeliverytermid() {
        return (String) getAttributeInternal(DELIVERYTERMID);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERYTERMID using the alias name Deliverytermid.
     * @param value value to set the DELIVERYTERMID
     */
    public void setDeliverytermid(String value) {
        setAttributeInternal(DELIVERYTERMID, value);
    }

    /**
     * Gets the attribute value for PAYMENTTERMID using the alias name Paymenttermid.
     * @return the PAYMENTTERMID
     */
    public String getPaymenttermid() {
        return (String) getAttributeInternal(PAYMENTTERMID);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENTTERMID using the alias name Paymenttermid.
     * @param value value to set the PAYMENTTERMID
     */
    public void setPaymenttermid(String value) {
        setAttributeInternal(PAYMENTTERMID, value);
    }

    /**
     * Gets the attribute value for RECE_STOREID using the alias name ReceStoreid.
     * @return the RECE_STOREID
     */
    public String getReceStoreid() {
        return (String) getAttributeInternal(RECESTOREID);
    }

    /**
     * Sets <code>value</code> as attribute value for RECE_STOREID using the alias name ReceStoreid.
     * @param value value to set the RECE_STOREID
     */
    public void setReceStoreid(String value) {
        setAttributeInternal(RECESTOREID, value);
    }

    /**
     * Gets the attribute value for PO_DATE using the alias name PoDate.
     * @return the PO_DATE
     */
    public Date getPoDate() {
        return (Date) getAttributeInternal(PODATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_DATE using the alias name PoDate.
     * @param value value to set the PO_DATE
     */
    public void setPoDate(Date value) {
        setAttributeInternal(PODATE, value);
    }

    /**
     * Gets the attribute value for POTYPE using the alias name Potype.
     * @return the POTYPE
     */
    public String getPotype() {
        return (String) getAttributeInternal(POTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for POTYPE using the alias name Potype.
     * @param value value to set the POTYPE
     */
    public void setPotype(String value) {
        setAttributeInternal(POTYPE, value);
    }

    /**
     * Gets the attribute value for POSTATUS using the alias name Postatus.
     * @return the POSTATUS
     */
    public String getPostatus() {
        return (String) getAttributeInternal(POSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTATUS using the alias name Postatus.
     * @param value value to set the POSTATUS
     */
    public void setPostatus(String value) {
        setAttributeInternal(POSTATUS, value);
    }

    /**
     * Gets the attribute value for SUPP_REFNO using the alias name SuppRefno.
     * @return the SUPP_REFNO
     */
    public String getSuppRefno() {
        return (String) getAttributeInternal(SUPPREFNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPP_REFNO using the alias name SuppRefno.
     * @param value value to set the SUPP_REFNO
     */
    public void setSuppRefno(String value) {
        setAttributeInternal(SUPPREFNO, value);
    }

    /**
     * Gets the attribute value for SUPP_REF_DATE using the alias name SuppRefDate.
     * @return the SUPP_REF_DATE
     */
    public Date getSuppRefDate() {
        return (Date) getAttributeInternal(SUPPREFDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPP_REF_DATE using the alias name SuppRefDate.
     * @param value value to set the SUPP_REF_DATE
     */
    public void setSuppRefDate(Date value) {
        setAttributeInternal(SUPPREFDATE, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @return the EXCHANGE_RATE
     */
    public Integer getExchangeRate() {
        return (Integer) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @param value value to set the EXCHANGE_RATE
     */
    public void setExchangeRate(Integer value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for POSTEDBY using the alias name Postedby.
     * @return the POSTEDBY
     */
    public String getPostedby() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTEDBY using the alias name Postedby.
     * @param value value to set the POSTEDBY
     */
    public void setPostedby(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for PO_FOR using the alias name PoFor.
     * @return the PO_FOR
     */
    public String getPoFor() {
        return (String) getAttributeInternal(POFOR);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_FOR using the alias name PoFor.
     * @param value value to set the PO_FOR
     */
    public void setPoFor(String value) {
        setAttributeInternal(POFOR, value);
    }

    /**
     * Gets the attribute value for PROD_ID using the alias name ProdId.
     * @return the PROD_ID
     */
    public String getProdId() {
        return (String) getAttributeInternal(PRODID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_ID using the alias name ProdId.
     * @param value value to set the PROD_ID
     */
    public void setProdId(String value) {
        setAttributeInternal(PRODID, value);
    }

    /**
     * Gets the attribute value for LC_BANKID using the alias name LcBankid.
     * @return the LC_BANKID
     */
    public String getLcBankid() {
        return (String) getAttributeInternal(LCBANKID);
    }

    /**
     * Sets <code>value</code> as attribute value for LC_BANKID using the alias name LcBankid.
     * @param value value to set the LC_BANKID
     */
    public void setLcBankid(String value) {
        setAttributeInternal(LCBANKID, value);
    }

    /**
     * Gets the attribute value for LC_BRANCHID using the alias name LcBranchid.
     * @return the LC_BRANCHID
     */
    public String getLcBranchid() {
        return (String) getAttributeInternal(LCBRANCHID);
    }

    /**
     * Sets <code>value</code> as attribute value for LC_BRANCHID using the alias name LcBranchid.
     * @param value value to set the LC_BRANCHID
     */
    public void setLcBranchid(String value) {
        setAttributeInternal(LCBRANCHID, value);
    }

    /**
     * Gets the attribute value for LC_REF using the alias name LcRef.
     * @return the LC_REF
     */
    public String getLcRef() {
        return (String) getAttributeInternal(LCREF);
    }

    /**
     * Sets <code>value</code> as attribute value for LC_REF using the alias name LcRef.
     * @param value value to set the LC_REF
     */
    public void setLcRef(String value) {
        setAttributeInternal(LCREF, value);
    }

    /**
     * Gets the attribute value for LC_FOR_ID using the alias name LcForId.
     * @return the LC_FOR_ID
     */
    public Integer getLcForId() {
        return (Integer) getAttributeInternal(LCFORID);
    }

    /**
     * Sets <code>value</code> as attribute value for LC_FOR_ID using the alias name LcForId.
     * @param value value to set the LC_FOR_ID
     */
    public void setLcForId(Integer value) {
        setAttributeInternal(LCFORID, value);
    }

    /**
     * Gets the attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @return the IS_MIGRATED
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @param value value to set the IS_MIGRATED
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @return the MIGRATED_DATE
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @param value value to set the MIGRATED_DATE
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for REF_ORDER_HEADER_ID using the alias name RefOrderHeaderId.
     * @return the REF_ORDER_HEADER_ID
     */
    public String getRefOrderHeaderId() {
        return (String) getAttributeInternal(REFORDERHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_ORDER_HEADER_ID using the alias name RefOrderHeaderId.
     * @param value value to set the REF_ORDER_HEADER_ID
     */
    public void setRefOrderHeaderId(String value) {
        setAttributeInternal(REFORDERHEADERID, value);
    }

    /**
     * Gets the attribute value for CYCLE_FOR using the alias name CycleFor.
     * @return the CYCLE_FOR
     */
    public String getCycleFor() {
        return (String) getAttributeInternal(CYCLEFOR);
    }

    /**
     * Sets <code>value</code> as attribute value for CYCLE_FOR using the alias name CycleFor.
     * @param value value to set the CYCLE_FOR
     */
    public void setCycleFor(String value) {
        setAttributeInternal(CYCLEFOR, value);
    }

    /**
     * Gets the attribute value for APPROVED_MEMO_WOLC_ID using the alias name ApprovedMemoWolcId.
     * @return the APPROVED_MEMO_WOLC_ID
     */
    public String getApprovedMemoWolcId() {
        return (String) getAttributeInternal(APPROVEDMEMOWOLCID);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVED_MEMO_WOLC_ID using the alias name ApprovedMemoWolcId.
     * @param value value to set the APPROVED_MEMO_WOLC_ID
     */
    public void setApprovedMemoWolcId(String value) {
        setAttributeInternal(APPROVEDMEMOWOLCID, value);
    }

    /**
     * Gets the attribute value for POSEQ using the alias name Poseq.
     * @return the POSEQ
     */
    public Integer getPoseq() {
        return (Integer) getAttributeInternal(POSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for POSEQ using the alias name Poseq.
     * @param value value to set the POSEQ
     */
    public void setPoseq(Integer value) {
        setAttributeInternal(POSEQ, value);
    }

    /**
     * Gets the attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @return the TXT_LOCATION_NAME
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @param value value to set the TXT_LOCATION_NAME
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for TXT_STORE_NAME using the alias name txtStoreName.
     * @return the TXT_STORE_NAME
     */
    public String gettxtStoreName() {
        return (String) getAttributeInternal(TXTSTORENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_STORE_NAME using the alias name txtStoreName.
     * @param value value to set the TXT_STORE_NAME
     */
    public void settxtStoreName(String value) {
        setAttributeInternal(TXTSTORENAME, value);
    }

    /**
     * Gets the attribute value for TXT_SUPPLIER_NAME using the alias name txtSupplierName.
     * @return the TXT_SUPPLIER_NAME
     */
    public String gettxtSupplierName() {
        return (String) getAttributeInternal(TXTSUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SUPPLIER_NAME using the alias name txtSupplierName.
     * @param value value to set the TXT_SUPPLIER_NAME
     */
    public void settxtSupplierName(String value) {
        setAttributeInternal(TXTSUPPLIERNAME, value);
    }

    /**
     * Gets the attribute value for TXT_SUM_QUANTITY using the alias name txtSumQuantity.
     * @return the TXT_SUM_QUANTITY
     */
    public Integer gettxtSumQuantity() {
        return (Integer) getAttributeInternal(TXTSUMQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SUM_QUANTITY using the alias name txtSumQuantity.
     * @param value value to set the TXT_SUM_QUANTITY
     */
    public void settxtSumQuantity(Integer value) {
        setAttributeInternal(TXTSUMQUANTITY, value);
    }

    /**
     * Gets the attribute value for TXT_SUM_NETMOUNT using the alias name txtSumNetmount.
     * @return the TXT_SUM_NETMOUNT
     */
    public BigDecimal gettxtSumNetmount() {
        return (BigDecimal) getAttributeInternal(TXTSUMNETMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SUM_NETMOUNT using the alias name txtSumNetmount.
     * @param value value to set the TXT_SUM_NETMOUNT
     */
    public void settxtSumNetmount(BigDecimal value) {
        setAttributeInternal(TXTSUMNETMOUNT, value);
    }

    /**
     * Gets the attribute value for TXT_SUM_GROSS_AMOUNT using the alias name txtSumGrossAmount.
     * @return the TXT_SUM_GROSS_AMOUNT
     */
    public BigDecimal gettxtSumGrossAmount() {
        return (BigDecimal) getAttributeInternal(TXTSUMGROSSAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SUM_GROSS_AMOUNT using the alias name txtSumGrossAmount.
     * @param value value to set the TXT_SUM_GROSS_AMOUNT
     */
    public void settxtSumGrossAmount(BigDecimal value) {
        setAttributeInternal(TXTSUMGROSSAMOUNT, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PuPoLinesVO.
     */
    public RowIterator getPuPoLinesVO() {
        return (RowIterator) getAttributeInternal(PUPOLINESVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllLocationsView.
     */
    public Row getAllLocationsView() {
        return (Row) getAttributeInternal(ALLLOCATIONSVIEW);
    }

    /**
     * Sets the master-detail link AllLocationsView between this object and <code>value</code>.
     */
    public void setAllLocationsView(Row value) {
        setAttributeInternal(ALLLOCATIONSVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AllStoresView.
     */
    public Row getAllStoresView() {
        return (Row) getAttributeInternal(ALLSTORESVIEW);
    }

    /**
     * Sets the master-detail link AllStoresView between this object and <code>value</code>.
     */
    public void setAllStoresView(Row value) {
        setAttributeInternal(ALLSTORESVIEW, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link PuSuppliersView.
     */
    public Row getPuSuppliersView() {
        return (Row) getAttributeInternal(PUSUPPLIERSVIEW);
    }

    /**
     * Sets the master-detail link PuSuppliersView between this object and <code>value</code>.
     */
    public void setPuSuppliersView(Row value) {
        setAttributeInternal(PUSUPPLIERSVIEW, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllPaymentTermsVO.
     */
    public RowSet getAccAllPaymentTermsVO() {
        return (RowSet) getAttributeInternal(ACCALLPAYMENTTERMSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllDeliveryTermsVO.
     */
    public RowSet getAccAllDeliveryTermsVO() {
        return (RowSet) getAttributeInternal(ACCALLDELIVERYTERMSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllLocationsView.
     */
    public RowSet getAccAllLocationsView() {
        return (RowSet) getAttributeInternal(ACCALLLOCATIONSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllStoresVO.
     */
    public RowSet getAccAllStoresVO() {
        return (RowSet) getAttributeInternal(ACCALLSTORESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccPuSuppliersView.
     */
    public RowSet getAccPuSuppliersView() {
        return (RowSet) getAttributeInternal(ACCPUSUPPLIERSVIEW);
    }
    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getPosted().equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

