package erpsolscm.erpsolscmmodel.erpsolscmvo;

import erpsolscm.erpsolscmmodel.erpsolscmvo.common.PuPurchaseReturnImeiVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 18 00:25:36 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PuPurchaseReturnImeiVOImpl extends ViewObjectImpl implements PuPurchaseReturnImeiVO {
    /**
     * This is the default constructor (do not remove).
     */
    public PuPurchaseReturnImeiVOImpl() {
    }
    
    public void doERPSolPORemoveBox() {
        try {
            //if selected box is null then exception will be handled
            String ERPSolBox = this.getCurrentRow().getAttribute("BoxNo").toString();
            this.setRangeSize(-1);

            for (int i = 0; i < this.getViewObject().getEstimatedRowCount(); i++) {
                try {//if row box no is null then system will move to next record in loop
                    if (getRowAtRangeIndex(i).getAttribute("BoxNo").toString().equals(ERPSolBox)) {
                        getRowAtRangeIndex(i).remove();
                        i--;
                    }
                } catch (Exception e) {
                    // TODO: Add catch code
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            // TODO: Add catch code
    //            e.printStackTrace();
        }

    }
}

