package erpsolscm.erpsolscmmodel.erpsolscmvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 18 00:26:32 PKT 2024
// ---------------------------------------------------------------------
public interface PuPurchaseReturnImeiVO extends ViewObject {
    void doERPSolPORemoveBox();
}

