package erpsolscm.erpsolscmmodel.erpsolscmvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 17 12:11:15 PKT 2024
// ---------------------------------------------------------------------
public interface PuPurchaseOrdersVO extends ViewObject {
    void doSupervisePurchaseOrder();
}

