package erpsolscm.erpsolscmmodel.erpsolscmvo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 18 10:42:55 PKT 2024
// ---------------------------------------------------------------------
public interface PuPurchaseReturnVO extends ViewObject {
    void doSupervisePurchaseReturn();
}

