package erpsolscm.erpsolscmmodel.erpsolscmeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 12 23:10:57 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PuPoLinesImpl  extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Poitemid,
        Poid,
        Dmditemid,
        Itemid,
        ItemType,
        DemandQty,
        OrderQty,
        ConfirmedQty,
        CancelQty,
        DeliveryDate,
        UnitPriceInFcurr,
        UnitPriceInBcurr,
        Hscode,
        HsRate,
        Remarks,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Polineno,
        Partid,
        GrnQty,
        LcNo,
        GdNo,
        AirwaysBillno,
        GrnNo,
        FocQty,
        ExtraQty,
        RefLcNo,
        ActPriceInFcurr,
        ActPriceInBcurr,
        MemoBillid,
        SaleTax,
        Discount,
        NetAmount,
        BarCode,
        GrossAmount,
        ExtraTax,
        Poseq,
        Polinesseq,
        txtModelNo,
        txtGrossAmount,
        txtNetAmount,
        txtProductId,
        txtPosted,
        PuPurchaseOrders,
        InItems,
        PuPurchaseOrderImei;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int POITEMID = AttributesEnum.Poitemid.index();
    public static final int POID = AttributesEnum.Poid.index();
    public static final int DMDITEMID = AttributesEnum.Dmditemid.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int ITEMTYPE = AttributesEnum.ItemType.index();
    public static final int DEMANDQTY = AttributesEnum.DemandQty.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int CONFIRMEDQTY = AttributesEnum.ConfirmedQty.index();
    public static final int CANCELQTY = AttributesEnum.CancelQty.index();
    public static final int DELIVERYDATE = AttributesEnum.DeliveryDate.index();
    public static final int UNITPRICEINFCURR = AttributesEnum.UnitPriceInFcurr.index();
    public static final int UNITPRICEINBCURR = AttributesEnum.UnitPriceInBcurr.index();
    public static final int HSCODE = AttributesEnum.Hscode.index();
    public static final int HSRATE = AttributesEnum.HsRate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int POLINENO = AttributesEnum.Polineno.index();
    public static final int PARTID = AttributesEnum.Partid.index();
    public static final int GRNQTY = AttributesEnum.GrnQty.index();
    public static final int LCNO = AttributesEnum.LcNo.index();
    public static final int GDNO = AttributesEnum.GdNo.index();
    public static final int AIRWAYSBILLNO = AttributesEnum.AirwaysBillno.index();
    public static final int GRNNO = AttributesEnum.GrnNo.index();
    public static final int FOCQTY = AttributesEnum.FocQty.index();
    public static final int EXTRAQTY = AttributesEnum.ExtraQty.index();
    public static final int REFLCNO = AttributesEnum.RefLcNo.index();
    public static final int ACTPRICEINFCURR = AttributesEnum.ActPriceInFcurr.index();
    public static final int ACTPRICEINBCURR = AttributesEnum.ActPriceInBcurr.index();
    public static final int MEMOBILLID = AttributesEnum.MemoBillid.index();
    public static final int SALETAX = AttributesEnum.SaleTax.index();
    public static final int DISCOUNT = AttributesEnum.Discount.index();
    public static final int NETAMOUNT = AttributesEnum.NetAmount.index();
    public static final int BARCODE = AttributesEnum.BarCode.index();
    public static final int GROSSAMOUNT = AttributesEnum.GrossAmount.index();
    public static final int EXTRATAX = AttributesEnum.ExtraTax.index();
    public static final int POSEQ = AttributesEnum.Poseq.index();
    public static final int POLINESSEQ = AttributesEnum.Polinesseq.index();
    public static final int TXTMODELNO = AttributesEnum.txtModelNo.index();
    public static final int TXTGROSSAMOUNT = AttributesEnum.txtGrossAmount.index();
    public static final int TXTNETAMOUNT = AttributesEnum.txtNetAmount.index();
    public static final int TXTPRODUCTID = AttributesEnum.txtProductId.index();
    public static final int TXTPOSTED = AttributesEnum.txtPosted.index();
    public static final int PUPURCHASEORDERS = AttributesEnum.PuPurchaseOrders.index();
    public static final int INITEMS = AttributesEnum.InItems.index();
    public static final int PUPURCHASEORDERIMEI = AttributesEnum.PuPurchaseOrderImei.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PuPoLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolscm.erpsolscmmodel.erpsolscmeo.PuPoLines");
    }


    /**
     * Gets the attribute value for Poitemid, using the alias name Poitemid.
     * @return the value of Poitemid
     */
    public String getPoitemid() {
        return (String) getAttributeInternal(POITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Poitemid.
     * @param value value to set the Poitemid
     */
    public void setPoitemid(String value) {
        setAttributeInternal(POITEMID, value);
    }

    /**
     * Gets the attribute value for Poid, using the alias name Poid.
     * @return the value of Poid
     */
    public String getPoid() {
        return (String) getAttributeInternal(POID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Poid.
     * @param value value to set the Poid
     */
    public void setPoid(String value) {
        setAttributeInternal(POID, value);
    }

    /**
     * Gets the attribute value for Dmditemid, using the alias name Dmditemid.
     * @return the value of Dmditemid
     */
    public String getDmditemid() {
        return (String) getAttributeInternal(DMDITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dmditemid.
     * @param value value to set the Dmditemid
     */
    public void setDmditemid(String value) {
        setAttributeInternal(DMDITEMID, value);
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for ItemType, using the alias name ItemType.
     * @return the value of ItemType
     */
    public String getItemType() {
        return (String) getAttributeInternal(ITEMTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemType.
     * @param value value to set the ItemType
     */
    public void setItemType(String value) {
        setAttributeInternal(ITEMTYPE, value);
    }

    /**
     * Gets the attribute value for DemandQty, using the alias name DemandQty.
     * @return the value of DemandQty
     */
    public Integer getDemandQty() {
        return (Integer) getAttributeInternal(DEMANDQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DemandQty.
     * @param value value to set the DemandQty
     */
    public void setDemandQty(Integer value) {
        setAttributeInternal(DEMANDQTY, value);
    }

    /**
     * Gets the attribute value for OrderQty, using the alias name OrderQty.
     * @return the value of OrderQty
     */
    public Integer getOrderQty() {
        return (Integer) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQty.
     * @param value value to set the OrderQty
     */
    public void setOrderQty(Integer value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for ConfirmedQty, using the alias name ConfirmedQty.
     * @return the value of ConfirmedQty
     */
    public Integer getConfirmedQty() {
        return (Integer) getAttributeInternal(CONFIRMEDQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConfirmedQty.
     * @param value value to set the ConfirmedQty
     */
    public void setConfirmedQty(Integer value) {
        setAttributeInternal(CONFIRMEDQTY, value);
    }

    /**
     * Gets the attribute value for CancelQty, using the alias name CancelQty.
     * @return the value of CancelQty
     */
    public Integer getCancelQty() {
        return (Integer) getAttributeInternal(CANCELQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CancelQty.
     * @param value value to set the CancelQty
     */
    public void setCancelQty(Integer value) {
        setAttributeInternal(CANCELQTY, value);
    }

    /**
     * Gets the attribute value for DeliveryDate, using the alias name DeliveryDate.
     * @return the value of DeliveryDate
     */
    public Date getDeliveryDate() {
        return (Date) getAttributeInternal(DELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate.
     * @param value value to set the DeliveryDate
     */
    public void setDeliveryDate(Date value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for UnitPriceInFcurr, using the alias name UnitPriceInFcurr.
     * @return the value of UnitPriceInFcurr
     */
    public BigDecimal getUnitPriceInFcurr() {
        return (BigDecimal) getAttributeInternal(UNITPRICEINFCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitPriceInFcurr.
     * @param value value to set the UnitPriceInFcurr
     */
    public void setUnitPriceInFcurr(BigDecimal value) {
        setAttributeInternal(UNITPRICEINFCURR, value);
    }

    /**
     * Gets the attribute value for UnitPriceInBcurr, using the alias name UnitPriceInBcurr.
     * @return the value of UnitPriceInBcurr
     */
    public BigDecimal getUnitPriceInBcurr() {
        return (BigDecimal) getAttributeInternal(UNITPRICEINBCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitPriceInBcurr.
     * @param value value to set the UnitPriceInBcurr
     */
    public void setUnitPriceInBcurr(BigDecimal value) {
        setAttributeInternal(UNITPRICEINBCURR, value);
    }

    /**
     * Gets the attribute value for Hscode, using the alias name Hscode.
     * @return the value of Hscode
     */
    public String getHscode() {
        return (String) getAttributeInternal(HSCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Hscode.
     * @param value value to set the Hscode
     */
    public void setHscode(String value) {
        setAttributeInternal(HSCODE, value);
    }

    /**
     * Gets the attribute value for HsRate, using the alias name HsRate.
     * @return the value of HsRate
     */
    public BigDecimal getHsRate() {
        return (BigDecimal) getAttributeInternal(HSRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HsRate.
     * @param value value to set the HsRate
     */
    public void setHsRate(BigDecimal value) {
        setAttributeInternal(HSRATE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for Polineno, using the alias name Polineno.
     * @return the value of Polineno
     */
    public Integer getPolineno() {
        return (Integer) getAttributeInternal(POLINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Polineno.
     * @param value value to set the Polineno
     */
    public void setPolineno(Integer value) {
        setAttributeInternal(POLINENO, value);
    }

    /**
     * Gets the attribute value for Partid, using the alias name Partid.
     * @return the value of Partid
     */
    public String getPartid() {
        return (String) getAttributeInternal(PARTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Partid.
     * @param value value to set the Partid
     */
    public void setPartid(String value) {
        setAttributeInternal(PARTID, value);
    }

    /**
     * Gets the attribute value for GrnQty, using the alias name GrnQty.
     * @return the value of GrnQty
     */
    public Integer getGrnQty() {
        return (Integer) getAttributeInternal(GRNQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrnQty.
     * @param value value to set the GrnQty
     */
    public void setGrnQty(Integer value) {
        setAttributeInternal(GRNQTY, value);
    }

    /**
     * Gets the attribute value for LcNo, using the alias name LcNo.
     * @return the value of LcNo
     */
    public String getLcNo() {
        return (String) getAttributeInternal(LCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LcNo.
     * @param value value to set the LcNo
     */
    public void setLcNo(String value) {
        setAttributeInternal(LCNO, value);
    }

    /**
     * Gets the attribute value for GdNo, using the alias name GdNo.
     * @return the value of GdNo
     */
    public String getGdNo() {
        return (String) getAttributeInternal(GDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for GdNo.
     * @param value value to set the GdNo
     */
    public void setGdNo(String value) {
        setAttributeInternal(GDNO, value);
    }

    /**
     * Gets the attribute value for AirwaysBillno, using the alias name AirwaysBillno.
     * @return the value of AirwaysBillno
     */
    public String getAirwaysBillno() {
        return (String) getAttributeInternal(AIRWAYSBILLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for AirwaysBillno.
     * @param value value to set the AirwaysBillno
     */
    public void setAirwaysBillno(String value) {
        setAttributeInternal(AIRWAYSBILLNO, value);
    }

    /**
     * Gets the attribute value for GrnNo, using the alias name GrnNo.
     * @return the value of GrnNo
     */
    public String getGrnNo() {
        return (String) getAttributeInternal(GRNNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrnNo.
     * @param value value to set the GrnNo
     */
    public void setGrnNo(String value) {
        setAttributeInternal(GRNNO, value);
    }

    /**
     * Gets the attribute value for FocQty, using the alias name FocQty.
     * @return the value of FocQty
     */
    public Integer getFocQty() {
        return (Integer) getAttributeInternal(FOCQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for FocQty.
     * @param value value to set the FocQty
     */
    public void setFocQty(Integer value) {
        setAttributeInternal(FOCQTY, value);
    }

    /**
     * Gets the attribute value for ExtraQty, using the alias name ExtraQty.
     * @return the value of ExtraQty
     */
    public Integer getExtraQty() {
        return (Integer) getAttributeInternal(EXTRAQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraQty.
     * @param value value to set the ExtraQty
     */
    public void setExtraQty(Integer value) {
        setAttributeInternal(EXTRAQTY, value);
    }

    /**
     * Gets the attribute value for RefLcNo, using the alias name RefLcNo.
     * @return the value of RefLcNo
     */
    public String getRefLcNo() {
        return (String) getAttributeInternal(REFLCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefLcNo.
     * @param value value to set the RefLcNo
     */
    public void setRefLcNo(String value) {
        setAttributeInternal(REFLCNO, value);
    }

    /**
     * Gets the attribute value for ActPriceInFcurr, using the alias name ActPriceInFcurr.
     * @return the value of ActPriceInFcurr
     */
    public BigDecimal getActPriceInFcurr() {
        return (BigDecimal) getAttributeInternal(ACTPRICEINFCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActPriceInFcurr.
     * @param value value to set the ActPriceInFcurr
     */
    public void setActPriceInFcurr(BigDecimal value) {
        setAttributeInternal(ACTPRICEINFCURR, value);
    }

    /**
     * Gets the attribute value for ActPriceInBcurr, using the alias name ActPriceInBcurr.
     * @return the value of ActPriceInBcurr
     */
    public BigDecimal getActPriceInBcurr() {
        return (BigDecimal) getAttributeInternal(ACTPRICEINBCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActPriceInBcurr.
     * @param value value to set the ActPriceInBcurr
     */
    public void setActPriceInBcurr(BigDecimal value) {
        setAttributeInternal(ACTPRICEINBCURR, value);
    }

    /**
     * Gets the attribute value for MemoBillid, using the alias name MemoBillid.
     * @return the value of MemoBillid
     */
    public String getMemoBillid() {
        return (String) getAttributeInternal(MEMOBILLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for MemoBillid.
     * @param value value to set the MemoBillid
     */
    public void setMemoBillid(String value) {
        setAttributeInternal(MEMOBILLID, value);
    }

    /**
     * Gets the attribute value for SaleTax, using the alias name SaleTax.
     * @return the value of SaleTax
     */
    public BigDecimal getSaleTax() {
        return (BigDecimal) getAttributeInternal(SALETAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for SaleTax.
     * @param value value to set the SaleTax
     */
    public void setSaleTax(BigDecimal value) {
        setAttributeInternal(SALETAX, value);
    }

    /**
     * Gets the attribute value for Discount, using the alias name Discount.
     * @return the value of Discount
     */
    public BigDecimal getDiscount() {
        return (BigDecimal) getAttributeInternal(DISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Discount.
     * @param value value to set the Discount
     */
    public void setDiscount(BigDecimal value) {
        setAttributeInternal(DISCOUNT, value);
    }

    /**
     * Gets the attribute value for NetAmount, using the alias name NetAmount.
     * @return the value of NetAmount
     */
    public BigDecimal getNetAmount() {
        return (BigDecimal) getAttributeInternal(NETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for NetAmount.
     * @param value value to set the NetAmount
     */
    public void setNetAmount(BigDecimal value) {
        setAttributeInternal(NETAMOUNT, value);
    }

    /**
     * Gets the attribute value for BarCode, using the alias name BarCode.
     * @return the value of BarCode
     */
    public String getBarCode() {
        return (String) getAttributeInternal(BARCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BarCode.
     * @param value value to set the BarCode
     */
    public void setBarCode(String value) {
        setAttributeInternal(BARCODE, value);
    }

    /**
     * Gets the attribute value for GrossAmount, using the alias name GrossAmount.
     * @return the value of GrossAmount
     */
    public BigDecimal getGrossAmount() {
        return (BigDecimal) getAttributeInternal(GROSSAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrossAmount.
     * @param value value to set the GrossAmount
     */
    public void setGrossAmount(BigDecimal value) {
        setAttributeInternal(GROSSAMOUNT, value);
    }

    /**
     * Gets the attribute value for ExtraTax, using the alias name ExtraTax.
     * @return the value of ExtraTax
     */
    public BigDecimal getExtraTax() {
        return (BigDecimal) getAttributeInternal(EXTRATAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraTax.
     * @param value value to set the ExtraTax
     */
    public void setExtraTax(BigDecimal value) {
        setAttributeInternal(EXTRATAX, value);
    }

    /**
     * Gets the attribute value for Poseq, using the alias name Poseq.
     * @return the value of Poseq
     */
    public Integer getPoseq() {
        return (Integer) getAttributeInternal(POSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Poseq.
     * @param value value to set the Poseq
     */
    public void setPoseq(Integer value) {
        setAttributeInternal(POSEQ, value);
    }

    /**
     * Gets the attribute value for Polinesseq, using the alias name Polinesseq.
     * @return the value of Polinesseq
     */
    public Integer getPolinesseq() {
        return (Integer) getAttributeInternal(POLINESSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Polinesseq.
     * @param value value to set the Polinesseq
     */
    public void setPolinesseq(Integer value) {
        setAttributeInternal(POLINESSEQ, value);
    }

    /**
     * Gets the attribute value for txtModelNo, using the alias name txtModelNo.
     * @return the value of txtModelNo
     */
    public String gettxtModelNo() {
        return (String) getAttributeInternal(TXTMODELNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtModelNo.
     * @param value value to set the txtModelNo
     */
    public void settxtModelNo(String value) {
        setAttributeInternal(TXTMODELNO, value);
    }

    /**
     * Gets the attribute value for txtGrossAmount, using the alias name txtGrossAmount.
     * @return the value of txtGrossAmount
     */
    public BigDecimal gettxtGrossAmount() {
        return (BigDecimal) getAttributeInternal(TXTGROSSAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtGrossAmount.
     * @param value value to set the txtGrossAmount
     */
    public void settxtGrossAmount(BigDecimal value) {
        setAttributeInternal(TXTGROSSAMOUNT, value);
    }

    /**
     * Gets the attribute value for txtNetAmount, using the alias name txtNetAmount.
     * @return the value of txtNetAmount
     */
    public BigDecimal gettxtNetAmount() {
        return (BigDecimal) getAttributeInternal(TXTNETAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtNetAmount.
     * @param value value to set the txtNetAmount
     */
    public void settxtNetAmount(BigDecimal value) {
        setAttributeInternal(TXTNETAMOUNT, value);
    }

    /**
     * Gets the attribute value for txtProductId, using the alias name txtProductId.
     * @return the value of txtProductId
     */
    public String gettxtProductId() {
        return (String) getAttributeInternal(TXTPRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtProductId.
     * @param value value to set the txtProductId
     */
    public void settxtProductId(String value) {
        setAttributeInternal(TXTPRODUCTID, value);
    }

    /**
     * Gets the attribute value for txtPosted, using the alias name txtPosted.
     * @return the value of txtPosted
     */
    public String gettxtPosted() {
        return (String) getAttributeInternal(TXTPOSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtPosted.
     * @param value value to set the txtPosted
     */
    public void settxtPosted(String value) {
        setAttributeInternal(TXTPOSTED, value);
    }

    /**
     * @return the associated entity PuPurchaseOrdersImpl.
     */
    public PuPurchaseOrdersImpl getPuPurchaseOrders() {
        return (PuPurchaseOrdersImpl) getAttributeInternal(PUPURCHASEORDERS);
    }

    /**
     * Sets <code>value</code> as the associated entity PuPurchaseOrdersImpl.
     */
    public void setPuPurchaseOrders(PuPurchaseOrdersImpl value) {
        setAttributeInternal(PUPURCHASEORDERS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getInItems() {
        return (EntityImpl) getAttributeInternal(INITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setInItems(EntityImpl value) {
        setAttributeInternal(INITEMS, value);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPuPurchaseOrderImei() {
        return (RowIterator) getAttributeInternal(PUPURCHASEORDERIMEI);
    }


    /**
     * @param polinesseq key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer polinesseq) {
        return new Key(new Object[] { polinesseq });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("Polinesseq");
        setERPSolPKSeqName("PU_PO_LINES_SEQ");
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
            populateAttributeAsChanged(POID, getPuPurchaseOrders().getPoid());
            
            String pkValue="'"+getPoid()+"'||'-'||nvl(max(to_number(substr(POItemId, length(POId)+2)))+1,1) ";
            System.out.println(pkValue + "pk value");
            String result= ERPSolGlobClassModel.doGetERPSolPrimaryKeyValueModel(getDBTransaction(), pkValue, "PU_PO_LINES", "POID", getPoid());
            populateAttributeAsChanged(POITEMID, result);
        }
         if (operation!=DML_DELETE) {
             System.out.println();
            populateAttributeAsChanged(UNITPRICEINFCURR, getUnitPriceInBcurr());
            populateAttributeAsChanged(GROSSAMOUNT, gettxtGrossAmount());
            populateAttributeAsChanged(NETAMOUNT, gettxtNetAmount());
            populateAttributeAsChanged(DEMANDQTY, getOrderQty());
            populateAttributeAsChanged(CONFIRMEDQTY, getOrderQty());
            populateAttributeAsChanged(ACTPRICEINBCURR, gettxtGrossAmount());
            populateAttributeAsChanged(ACTPRICEINFCURR, gettxtGrossAmount());



           
        }
        super.doDML(operation, e);
    }
}

