package erpsolscm.erpsolscmmodel.erpsolscmeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 14 16:15:58 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PuPurchaseReturnLinesImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PrId,
        Lineno,
        Itemid,
        SourceQty,
        ReturnQty,
        UnitPriceInFcurr,
        UnitPriceInBcurr,
        Polineno,
        Grnlineno,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        QtyIssued,
        Poseqno,
        Prlineseqno,
        txtAmount,
        Prseqno,
        txtModelNo,
        txtProductId,
        PuPurchaseReturn,
        InItems;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PRID = AttributesEnum.PrId.index();
    public static final int LINENO = AttributesEnum.Lineno.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int SOURCEQTY = AttributesEnum.SourceQty.index();
    public static final int RETURNQTY = AttributesEnum.ReturnQty.index();
    public static final int UNITPRICEINFCURR = AttributesEnum.UnitPriceInFcurr.index();
    public static final int UNITPRICEINBCURR = AttributesEnum.UnitPriceInBcurr.index();
    public static final int POLINENO = AttributesEnum.Polineno.index();
    public static final int GRNLINENO = AttributesEnum.Grnlineno.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int QTYISSUED = AttributesEnum.QtyIssued.index();
    public static final int POSEQNO = AttributesEnum.Poseqno.index();
    public static final int PRLINESEQNO = AttributesEnum.Prlineseqno.index();
    public static final int TXTAMOUNT = AttributesEnum.txtAmount.index();
    public static final int PRSEQNO = AttributesEnum.Prseqno.index();
    public static final int TXTMODELNO = AttributesEnum.txtModelNo.index();
    public static final int TXTPRODUCTID = AttributesEnum.txtProductId.index();
    public static final int PUPURCHASERETURN = AttributesEnum.PuPurchaseReturn.index();
    public static final int INITEMS = AttributesEnum.InItems.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PuPurchaseReturnLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolscm.erpsolscmmodel.erpsolscmeo.PuPurchaseReturnLines");
    }


    /**
     * Gets the attribute value for PrId, using the alias name PrId.
     * @return the value of PrId
     */
    public String getPrId() {
        return (String) getAttributeInternal(PRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrId.
     * @param value value to set the PrId
     */
    public void setPrId(String value) {
        setAttributeInternal(PRID, value);
    }

    /**
     * Gets the attribute value for Lineno, using the alias name Lineno.
     * @return the value of Lineno
     */
    public Integer getLineno() {
        return (Integer) getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Lineno.
     * @param value value to set the Lineno
     */
    public void setLineno(Integer value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for SourceQty, using the alias name SourceQty.
     * @return the value of SourceQty
     */
    public Integer getSourceQty() {
        return (Integer) getAttributeInternal(SOURCEQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SourceQty.
     * @param value value to set the SourceQty
     */
    public void setSourceQty(Integer value) {
        setAttributeInternal(SOURCEQTY, value);
    }

    /**
     * Gets the attribute value for ReturnQty, using the alias name ReturnQty.
     * @return the value of ReturnQty
     */
    public Integer getReturnQty() {
        return (Integer) getAttributeInternal(RETURNQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReturnQty.
     * @param value value to set the ReturnQty
     */
    public void setReturnQty(Integer value) {
        setAttributeInternal(RETURNQTY, value);
    }

    /**
     * Gets the attribute value for UnitPriceInFcurr, using the alias name UnitPriceInFcurr.
     * @return the value of UnitPriceInFcurr
     */
    public BigDecimal getUnitPriceInFcurr() {
        return (BigDecimal) getAttributeInternal(UNITPRICEINFCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitPriceInFcurr.
     * @param value value to set the UnitPriceInFcurr
     */
    public void setUnitPriceInFcurr(BigDecimal value) {
        setAttributeInternal(UNITPRICEINFCURR, value);
    }

    /**
     * Gets the attribute value for UnitPriceInBcurr, using the alias name UnitPriceInBcurr.
     * @return the value of UnitPriceInBcurr
     */
    public BigDecimal getUnitPriceInBcurr() {
        return (BigDecimal) getAttributeInternal(UNITPRICEINBCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitPriceInBcurr.
     * @param value value to set the UnitPriceInBcurr
     */
    public void setUnitPriceInBcurr(BigDecimal value) {
        setAttributeInternal(UNITPRICEINBCURR, value);
    }

    /**
     * Gets the attribute value for Polineno, using the alias name Polineno.
     * @return the value of Polineno
     */
    public Integer getPolineno() {
        return (Integer) getAttributeInternal(POLINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Polineno.
     * @param value value to set the Polineno
     */
    public void setPolineno(Integer value) {
        setAttributeInternal(POLINENO, value);
    }

    /**
     * Gets the attribute value for Grnlineno, using the alias name Grnlineno.
     * @return the value of Grnlineno
     */
    public Integer getGrnlineno() {
        return (Integer) getAttributeInternal(GRNLINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Grnlineno.
     * @param value value to set the Grnlineno
     */
    public void setGrnlineno(Integer value) {
        setAttributeInternal(GRNLINENO, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for QtyIssued, using the alias name QtyIssued.
     * @return the value of QtyIssued
     */
    public Integer getQtyIssued() {
        return (Integer) getAttributeInternal(QTYISSUED);
    }

    /**
     * Sets <code>value</code> as the attribute value for QtyIssued.
     * @param value value to set the QtyIssued
     */
    public void setQtyIssued(Integer value) {
        setAttributeInternal(QTYISSUED, value);
    }

    /**
     * Gets the attribute value for Poseqno, using the alias name Poseqno.
     * @return the value of Poseqno
     */
    public Integer getPoseqno() {
        return (Integer) getAttributeInternal(POSEQNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Poseqno.
     * @param value value to set the Poseqno
     */
    public void setPoseqno(Integer value) {
        setAttributeInternal(POSEQNO, value);
    }

    /**
     * Gets the attribute value for Prlineseqno, using the alias name Prlineseqno.
     * @return the value of Prlineseqno
     */
    public Integer getPrlineseqno() {
        return (Integer) getAttributeInternal(PRLINESEQNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Prlineseqno.
     * @param value value to set the Prlineseqno
     */
    public void setPrlineseqno(Integer value) {
        setAttributeInternal(PRLINESEQNO, value);
    }

    /**
     * Gets the attribute value for txtAmount, using the alias name txtAmount.
     * @return the value of txtAmount
     */
    public String gettxtAmount() {
        return (String) getAttributeInternal(TXTAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtAmount.
     * @param value value to set the txtAmount
     */
    public void settxtAmount(String value) {
        setAttributeInternal(TXTAMOUNT, value);
    }

    /**
     * Gets the attribute value for Prseqno, using the alias name Prseqno.
     * @return the value of Prseqno
     */
    public Integer getPrseqno() {
        return (Integer) getAttributeInternal(PRSEQNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Prseqno.
     * @param value value to set the Prseqno
     */
    public void setPrseqno(Integer value) {
        setAttributeInternal(PRSEQNO, value);
    }

    /**
     * Gets the attribute value for txtModelNo, using the alias name txtModelNo.
     * @return the value of txtModelNo
     */
    public String gettxtModelNo() {
        return (String) getAttributeInternal(TXTMODELNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtModelNo.
     * @param value value to set the txtModelNo
     */
    public void settxtModelNo(String value) {
        setAttributeInternal(TXTMODELNO, value);
    }

    /**
     * Gets the attribute value for txtProductId, using the alias name txtProductId.
     * @return the value of txtProductId
     */
    public String gettxtProductId() {
        return (String) getAttributeInternal(TXTPRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtProductId.
     * @param value value to set the txtProductId
     */
    public void settxtProductId(String value) {
        setAttributeInternal(TXTPRODUCTID, value);
    }

    /**
     * @return the associated entity PuPurchaseReturnImpl.
     */
    public PuPurchaseReturnImpl getPuPurchaseReturn() {
        return (PuPurchaseReturnImpl) getAttributeInternal(PUPURCHASERETURN);
    }

    /**
     * Sets <code>value</code> as the associated entity PuPurchaseReturnImpl.
     */
    public void setPuPurchaseReturn(PuPurchaseReturnImpl value) {
        setAttributeInternal(PUPURCHASERETURN, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getInItems() {
        return (EntityImpl) getAttributeInternal(INITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setInItems(EntityImpl value) {
        setAttributeInternal(INITEMS, value);
    }


    /**
     * @param prlineseqno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer prlineseqno) {
        return new Key(new Object[] { prlineseqno });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("Prlineseqno");
        setERPSolPKSeqName("PU_PURCHASE_RETURN_LINES_SEQ");
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
            populateAttributeAsChanged(PRID, getPuPurchaseReturn().getPrId());
            
            String pkValue="FUNC_GET_MAX_ID('PU_PURCHASE_RETURN_LINES WHERE PR_ID=''"+getPrId()+"''','LINENO')";
            String result= ERPSolGlobClassModel.doGetERPSolPrimaryKeyValueModel(getDBTransaction(), pkValue, "dual", null, null);
            populateAttributeAsChanged(LINENO, Integer.parseInt(result));
            
        }
         if (operation!=DML_UPDATE) {
            populateAttributeAsChanged(UNITPRICEINFCURR, getUnitPriceInBcurr());
//            populateAttributeAsChanged(GROSSAMOUNT, gettxtGrossAmount());
//            populateAttributeAsChanged(NETAMOUNT, gettxtNetAmount());
//            populateAttributeAsChanged(DEMANDQTY, getOrderQty());
//            populateAttributeAsChanged(CONFIRMEDQTY, getConfirmedQty());


           
        }
        super.doDML(operation, e);
    }
}

