package erpsolscm.erpsolscmmodel.erpsolscmeo;

import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobClassModel;
import erpsolglob.erpsolglobmodel.erpsolglobclasses.ERPSolGlobalsEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 15 13:19:27 PKT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PuPurchaseOrderImeiImpl extends ERPSolGlobalsEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Poimeiseqno,
        InvalidImei,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Imei,
        ErrorDescription,
        CompanyCode,
        Itemid,
        ItemRefId,
        Polineseqno,
        Poseq,
        PuPoLines;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int POIMEISEQNO = AttributesEnum.Poimeiseqno.index();
    public static final int INVALIDIMEI = AttributesEnum.InvalidImei.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int IMEI = AttributesEnum.Imei.index();
    public static final int ERRORDESCRIPTION = AttributesEnum.ErrorDescription.index();
    public static final int COMPANYCODE = AttributesEnum.CompanyCode.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int ITEMREFID = AttributesEnum.ItemRefId.index();
    public static final int POLINESEQNO = AttributesEnum.Polineseqno.index();
    public static final int POSEQ = AttributesEnum.Poseq.index();
    public static final int PUPOLINES = AttributesEnum.PuPoLines.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PuPurchaseOrderImeiImpl() {
    }

    /**
     * Gets the attribute value for Poimeiseqno, using the alias name Poimeiseqno.
     * @return the value of Poimeiseqno
     */
    public Integer getPoimeiseqno() {
        return (Integer) getAttributeInternal(POIMEISEQNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Poimeiseqno.
     * @param value value to set the Poimeiseqno
     */
    public void setPoimeiseqno(Integer value) {
        setAttributeInternal(POIMEISEQNO, value);
    }

    /**
     * Gets the attribute value for InvalidImei, using the alias name InvalidImei.
     * @return the value of InvalidImei
     */
    public String getInvalidImei() {
        return (String) getAttributeInternal(INVALIDIMEI);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvalidImei.
     * @param value value to set the InvalidImei
     */
    public void setInvalidImei(String value) {
        setAttributeInternal(INVALIDIMEI, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for Imei, using the alias name Imei.
     * @return the value of Imei
     */
    public String getImei() {
        return (String) getAttributeInternal(IMEI);
    }

    /**
     * Sets <code>value</code> as the attribute value for Imei.
     * @param value value to set the Imei
     */
    public void setImei(String value) {
        setAttributeInternal(IMEI, value);
    }

    /**
     * Gets the attribute value for ErrorDescription, using the alias name ErrorDescription.
     * @return the value of ErrorDescription
     */
    public String getErrorDescription() {
        return (String) getAttributeInternal(ERRORDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ErrorDescription.
     * @param value value to set the ErrorDescription
     */
    public void setErrorDescription(String value) {
        setAttributeInternal(ERRORDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for CompanyCode, using the alias name CompanyCode.
     * @return the value of CompanyCode
     */
    public String getCompanyCode() {
        return (String) getAttributeInternal(COMPANYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyCode.
     * @param value value to set the CompanyCode
     */
    public void setCompanyCode(String value) {
        setAttributeInternal(COMPANYCODE, value);
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for ItemRefId, using the alias name ItemRefId.
     * @return the value of ItemRefId
     */
    public String getItemRefId() {
        return (String) getAttributeInternal(ITEMREFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemRefId.
     * @param value value to set the ItemRefId
     */
    public void setItemRefId(String value) {
        setAttributeInternal(ITEMREFID, value);
    }

    /**
     * Gets the attribute value for Polineseqno, using the alias name Polineseqno.
     * @return the value of Polineseqno
     */
    public Integer getPolineseqno() {
        return (Integer) getAttributeInternal(POLINESEQNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Polineseqno.
     * @param value value to set the Polineseqno
     */
    public void setPolineseqno(Integer value) {
        setAttributeInternal(POLINESEQNO, value);
    }

    /**
     * Gets the attribute value for Poseq, using the alias name Poseq.
     * @return the value of Poseq
     */
    public Integer getPoseq() {
        return (Integer) getAttributeInternal(POSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Poseq.
     * @param value value to set the Poseq
     */
    public void setPoseq(Integer value) {
        setAttributeInternal(POSEQ, value);
    }

    /**
     * @return the associated entity PuPoLinesImpl.
     */
    public PuPoLinesImpl getPuPoLines() {
        return (PuPoLinesImpl) getAttributeInternal(PUPOLINES);
    }

    /**
     * Sets <code>value</code> as the associated entity PuPoLinesImpl.
     */
    public void setPuPoLines(PuPoLinesImpl value) {
        setAttributeInternal(PUPOLINES, value);
    }

    /**
     * @param poimeiseqno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer poimeiseqno) {
        return new Key(new Object[] { poimeiseqno });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpsolscm.erpsolscmmodel.erpsolscmeo.PuPurchaseOrderImei");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        setERPSolPKColumnName("Poimeiseqno");
        setERPSolPKSeqName("PU_PURCHASE_ORDER_IMEI_SEQ");
        setCompanyCode(ERPSolGlobClassModel.doGetUserCompanyCode());
        setPoseq(getPuPoLines().getPoseq());
        
        super.create(attributeList);
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

